# Generated by Django 2.2.4 on 2020-09-21 19:33

from django.db import migrations


def fill_owner_table(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20200921_2232'),
    ]

    operations = [
        migrations.RunPython(fill_owner_table)
    ]
